services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules

